### ISSUE TITLE
unhandled exceptions

### ISSUE THREAD

**Issue by madhav-vl** [UlisesGascon/check-my-headers#19]
It's not handling the exception when passed an invalid url (e.g: https://random.tld)

`app.get("/check-header", (req, res, next) => {
  const url = 'https://random.tld';
  console.log(`======================== ${url} ==============================`);

  checkMyHeaders(url).then(({ messages, headers, status }) => {
    if (!messages || !headers) {
      res.send("error occurred");
    }

    res.send(headers);
  });
});`

![exception1](https://user-images.githubusercontent.com/60141341/97427510-ac08fd80-193a-11eb-9e75-c72ea86eb183.png)

**Comment by UlisesGascon** [comment]
Hi @madhav-vl! You can use `.catch()` to handle the errors...

```js
app.get("/check-header", (req, res, next) => { 
    const url = 'https://random.tld'; 
    console.log(======================== ${url} ==============================`);
    checkMyHeaders(url)
    .then(({ messages, headers, status }) => {
        res.send(headers);
    })
    .catch(err => {
       console.log("Error during http analysis:", err)
       res.status(500).send('error occurred')
    });
});
```
