### ISSUE TITLE
Honor intermediate CA (certification authorities) from environment variables

### ISSUE THREAD

**Issue by lfservin** [UlisesGascon/check-my-headers#20]
Some of us work behind intercepting proxies which break up HTTPS for scanning outgoing traffic and then self-sign all hosts in the internet. It's quite common.

Given the Certification authorities are known, when I set them up and call "sudo update-ca-certificates" and these environment variables have been set: NODE_EXTRA_CA_CERTS and REQUESTS_CA_BUNDLE, most applications are able to use these certification authorities to establish secure connections to the server. 

check-my-headers doesn't honor these environment variables and thus sends this message :

> CRITICAL ERROR:
> RequestError: Error: certificate signature failure

This would allow for better testing behind such proxies

**Comment by UlisesGascon** [comment]
Hi @lfservin! I believe that module `node_extra_ca_certs_mozilla_bundle` can help you. [See this thread for full reference]( https://github.com/request/request/issues/3106#issuecomment-568843004)
