### ISSUE TITLE
Refactor Headers Rules

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/check-my-headers#6]
### Pending
- [x] [Review rules](https://github.com/UlisesGascon/check-my-headers/blob/master/src/rules.json) with @lirantal
- [x] Make rules as external dependency

**Comment by lirantal** [comment]
Nice collection already!

We can also add feature policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy)

**Comment by lirantal** [comment]
If we end up having scores for this then I think we can make a review note in the future for the items across mandatory and optional and move them around.

**Comment by UlisesGascon** [comment]
Thanks for your suggestion @lirantal :-)

I will submit a PR asap for version v0.1.1 to include this rule.  I moved the discussion for scores to #7
